export const FETCH_LIKED = 'FETCH_LIKED'
export const FETCH_LIKED_SUCCESS = 'FETCH_LIKED_SUCCESS'
export const FETCH_LIKE_FAILURE = 'FETCH_LIKE_FAILURE'
export const POST_COMMENT_LIKED_TWEET = 'POST_COMMENT_LIKED_TWEET'